# CI on Windows via appveyor
environment:

    matrix:
        ## MINGW
        #
      - PYTHON: "C:\\Python27"
        PYTHON_VERSION: "2.7"
      - PYTHON: "C:\\Python34-x64"
        PYTHON_VERSION: "3.4"
      - PYTHON: "C:\\Python35-x64"
        PYTHON_VERSION: "3.5"
      - PYTHON: "C:\\Miniconda35-x64"
        PYTHON_VERSION: "3.5"
        IS_CONDA: "yes"

install:
    - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

    ## Print configuration for debugging.
    #
    - |
        echo %PATH%
        uname -a
        where python pip pip2 pip3 pip34
        python --version
        python -c "import struct; print(struct.calcsize('P') * 8)"

    - IF "%IS_CONDA%"=="yes" (
        conda info -a &
        conda install --yes --quiet  pip
      )
    - pip install  nose wheel coveralls

    ## For commits performed with the default user.
    - |
        git config --global user.email "travis@ci.com"
        git config --global user.name "Travis Runner"

    - pip install -e .

build: false

test_script:
    -   IF "%PYTHON_VERSION%"=="3.5" (
            nosetests -v --with-coverage
        ) ELSE (
            nosetests -v
        )
